argocd:
  name: argo-cd
  namespace: argo-cd
  version: 5.26.0
  values:
    global:
      hostAliases:
      - ip: 10.100.3.133
        hostnames:
        - git.kub-poc.local
        - sentry.kub-poc.local
        - argo-cd.kub-poc.local
        - grafana.kub-poc.local
        - prometheus.kub-poc.local
    server:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/issuer: "kub-poc-issuer"
        hosts:
          - argo-cd.kub-poc.local
        tls:
        - hosts:
            - argo-cd.kub-poc.local
          secretName: argo-cd-server-tls
        https: true
    configs:
      params:
        server.insecure: "false"
      cm:
        url: https://argo-cd.kub-poc.local
      notifications:
        argocdUrl: https://argo-cd.kub-poc.local
gitea:
  name: gitea
  namespace: git
  version: 7.0.4
  values:
    gitea:
      config:
        server:
          SSH_DOMAIN: git.kub-poc.local
          ROOT_URL: https://git.kub-poc.local
          DOMAIN: git.kub-poc.local
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: "kub-poc-issuer"
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - git.kub-poc.local
      tls:
        - hosts:
            - git.kub-poc.local
          secretName: git-tls
sentry:
  name: sentry
  namespace: monitoring
  version: 17.9.1
  values:
    ingress:
      enabled: true
      regexPathStyle: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - sentry.kub-poc.local
      tls:
      - secretName: sentry-tls
        hosts:
          - sentry.kub-poc.local
prometheus:
  name: prometheus
  namespace: monitoring
  version: 45.5.0
  values: {}
ingress:
  name: ingress-nginx
  namespace: ingress-nginx
  version: 4.5.2
  values:
    controller:
      service:
        loadBalancerIP: 10.100.3.133
      extraArgs:
        enable-ssl-passthrough: "true"
      config:
        use-forwarded-headers: "true"
        ssl-redirect: "true"
        force-ssl-redirect: "true"
        ssl-passthrough: "true"