apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
  creationTimestamp: "2023-03-24T13:43:13Z"
  generation: 8
  name: demo-test
  namespace: appservice-ns
  ownerReferences:
  - apiVersion: k8se.microsoft.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: App
    name: avladutestmssql2019
    uid: 36755db2-3b2a-4330-a89f-40ed77a639c2
  resourceVersion: "73825"
  uid: e854ebe5-e4d8-447a-b234-538add46f559
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: avladutestmssql2019
      k8se.microsoft.com/owner: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        appsettings-resourceVersion: "62249"
        fluentbit.io/exclude: "false"
        fluentbit.io/exclude_stdout-probe-shim: "true"
        kind: apps
      creationTimestamp: null
      labels:
        app: avladutestmssql2019
        k8se.microsoft.com/environmentName: production
        k8se.microsoft.com/owner: app
        min-replicas-billing: "1"
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: WEBSITE_SSH_PASSWORD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ASPNETCORE_URLS
          value: http://+:1433
        - name: PORT
          value: "1433"
        - name: WEBSITE_SITE_NAME
          value: avladutestmssql2019
        - name: APP_NAME
          value: avladutestmssql2019
        - name: WEBSITE_SLOT_NAME
          value: production
        - name: WEBSITE_HOSTNAME
          value: avladutestmssql2019.kubpocavladu1-ku-3u325qa.westeurope.k4apps.io
        - name: ENVIRONMENT_DNS_SUFFIX
          value: kubpocavladu1-ku-3u325qa.westeurope.k4apps.io
        - name: SCM_WEBSITE_HOSTNAME
          value: avladutestmssql2019.scm.kubpocavladu1-ku-3u325qa.westeurope.k4apps.io
        - name: MSSQL_MEMORYLIMIT_MB
          value: "2000"
        envFrom:
        - secretRef:
            name: avladutestmssql2019-secrets
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 1433
          timeoutSeconds: 1
        name: http
        ports:
        - containerPort: 1433
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 48
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 1433
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 3Gi
          requests:
            cpu: "2"
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: avladutestmssql2019
      serviceAccountName: avladutestmssql2019
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-03-24T13:43:13Z"
    lastUpdateTime: "2023-03-24T13:43:13Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-03-24T13:59:34Z"
    lastUpdateTime: "2023-03-24T13:59:34Z"
    message: ReplicaSet "avladutestmssql2019-67d967748b" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 8
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
