apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win10-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10-vm
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: vmdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 12G
      volumes:
      - name: vmdisk
        persistentVolumeClaim:
          claimName: win10-base-qcow2
