apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: kub-poc-control-plane
  namespace: tink-system
spec:
  kubeadmConfigSpec:
    format: ignition
    clusterConfiguration: {}
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: PROVIDER_ID
    joinConfiguration:
      nodeRegistration:
        ignorePreflightErrors:
        - DirAvailable--etc-kubernetes-manifests
        kubeletExtraArgs:
          provider-id: PROVIDER_ID
    preKubeadmCommands:
    - mkdir -p /etc/kubernetes/manifests && ctr images pull ghcr.io/kube-vip/kube-vip:v0.5.11
      && ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.5.11 vip /kube-vip manifest
      pod --arp --interface $(ip -4 -j route list default | jq -r .[0].dev) --address
      10.100.3.140 --controlplane --leaderElection > /etc/kubernetes/manifests/kube-vip.yaml
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: TinkerbellMachineTemplate
      name: kub-poc-control-plane
  replicas: 1
  version: v1.23.15
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellMachineTemplate
metadata:
  name: kub-poc-control-plane
  namespace: tink-system
spec:
  template:
    spec:
     imageLookupOSVersion: stable337424
     imageLookupOSDistro: flatcar
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kub-poc
  namespace: tink-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 172.26.0.0/16
  controlPlaneEndpoint:
    host: 10.100.3.140
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: kub-poc-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: TinkerbellCluster
    name: kub-poc
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellCluster
metadata:
  name: kub-poc
  namespace: tink-system
spec:
  imageLookupBaseRegistry: tinkerbell.azurecr.io/cluster-api-provider-tinkerbell-flatcar
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: kub-poc
    pool: worker-a
  name: kub-poc-worker-a
  namespace: tink-system
spec:
  clusterName: kub-poc
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: kub-poc
      pool: worker-a
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: kub-poc
        pool: worker-a
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: kub-poc-worker-a
      clusterName: kub-poc
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: TinkerbellMachineTemplate
        name: kub-poc-worker-a
      version: v1.26.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellMachineTemplate
metadata:
  name: kub-poc-worker-a
  namespace: tink-system
spec:
  template:
    spec:
     imageLookupOSVersion: stable337424
     imageLookupOSDistro: flatcar
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: kub-poc-worker-a
  namespace: tink-system
spec:
  template:
    spec:
      format: ignition
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            provider-id: PROVIDER_ID
