---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-cluster
spec:
  destination:
    namespace: tink-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/cluster
    repoURL: https://git.kub-poc.local/gitea_admin/k8s-metal.git
    targetRevision: HEAD