---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.ingress-nginx.name }}
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: {{ .Values.ingress-nginx.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: {{ .Values.ingress-nginx.version }}
    helm:
      valueFiles:
        - values.yaml
      values: |-
        {{- toYaml .Values.ingress-nginx.values | nindent 8 }}
