apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bird
  name: kube-system
data:
  config: |
        # This is a minimal configuration file, which allows the bird daemon to start
        # but will not cause anything else to happen.
        #
        # Please refer to the documentation in the bird-doc package or BIRD User's
        # Guide on http://bird.network.cz/ for more information on configuring BIRD and
        # adding routing protocols.

        # Change this into your BIRD router ID. It's a world-wide unique identification
        # of your router, usually one of router's IPv4 addresses.
        router id 10.100.3.50; # BGPRouter Node IP

        define my_as=65000; # BGPRouter Node AS -> can be set by us, but needs to be from 64512 to 65534, since those are for private use

        protocol direct{
                interface "*";
        }
        # The Kernel protocol is not a real routing protocol. Instead of communicating
        # with other routers in the network, it performs synchronization of BIRD's
        # routing tables with the OS kernel.
        protocol kernel {
                persist on;
                scan time 30;
                import all;
                learn;
                export all;
        }

        # The Device protocol is not a real routing protocol. It doesn't generate any
        # routes and it only serves as a module for getting information about network
        # interfaces from the kernel.
        protocol device {
                scan time 20;
        }

        template bgp TEMPLATE_BGP{
                debug { states, events };
                #table master;
                router id 10.100.3.50;
                description "IXNFO_COM";
                local as my_as;

                hold time 60;
                startup hold time 60;
                connect retry time 120;
                keepalive time 20;
                connect delay time 5;
                error wait time 60, 300;
                error forget time 300;
                next hop self;
                path metric 1;
                default bgp_med 0;

                export all;
                import all;

                #gateway direct;
        }

        protocol bgp IXNFO_COM from TEMPLATE_BGP{
                neighbor 10.100.3.51 as 65200; # First node in the cluster and the AS number of it
        }

        protocol bgp IXNFO_COM2 from TEMPLATE_BGP{
                neighbor 10.100.3.52 as 65200; # Second node in the cluster and the AS number of it
        }

        # logging
        log syslog { debug, trace, info, remote, warning, error, auth, fatal, bug };
        log stderr all;
        log "/var/log/bird.log" all;