---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-cluster-manifests
spec:
  destination:
    namespace: rook-ceph
    server: https://10.100.3.140:6443
  project: default
  source:
    path: config/workload/ceph-cluster
    repoURL: https://git.mgmt.kub-poc.local/gitea_admin/k8s-metal.git
    targetRevision: HEAD